version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_docker
    hostname: rabbit.local
    # restart: always
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672
